version: '3.8'
services:
  api-go:
    tty: true
    build: .
    volumes:
     - .:/go/api-go/
    links:
     - go-mysql
    networks: 
     - api-go-network
  go-mysql:
    image: mysql
    volumes:
     - ./database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_DATABASE=api-go
    ports:
     - 3306:3306
    networks: 
     - api-go-network
  
networks:
  api-go-network:
    driver: "bridge"
    name: api-go-network
